"""VNBOT Domain — Reminder entity and value objects.

Reminder ≠ Occurrence. Recurring reminders are RULES, not duplicated rows.
The scheduler generates occurrences with a 30-day lookahead window.

Key invariant: occurrence_key is deterministic {reminder_id}:{due_at_utc}:{rule_version}.
This guarantees idempotent delivery: the same occurrence fires exactly once.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Literal
from uuid import UUID, uuid4

from .common import utc_now, Authority, Provenance, Sensitivity


# ──────────────────────────────────────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────────────────────────────────────


class ReminderStatus(str, Enum):
    """Reminder lifecycle (per docs/07)."""

    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class ReminderPriority(str, Enum):
    """Reminder priority (per docs/07)."""

    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"


class ReminderChannel(str, Enum):
    """Delivery channel (per docs/07)."""

    WEB_PUSH = "web_push"
    DESKTOP = "desktop"
    ANDROID = "android"
    EMAIL = "email"
    TELEGRAM = "telegram"
    WHATSAPP = "whatsapp"
    MOCK = "mock"  # for dev/testing in Phase 0.1


class OccurrenceStatus(str, Enum):
    """ReminderOccurrence lifecycle (per docs/07)."""

    PENDING = "pending"
    QUEUED = "queued"
    SENDING = "sending"
    DELIVERED = "delivered"
    SNOOZED = "snoozed"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class RecurrenceFrequency(str, Enum):
    """RFC 5545-inspired frequency (subset for MVP)."""

    NONE = "none"  # one-off
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    YEARLY = "yearly"


# ──────────────────────────────────────────────────────────────────────────────
# Recurrence rule
# ──────────────────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class RecurrenceRule:
    """RRULE-inspired recurrence rule (subset for MVP).

    For full RRULE support in 0.5+, use python-dateutil's rrule.

    rule_version is bumped whenever the rule changes. This invalidates
    occurrence_keys derived from the old rule.
    """

    frequency: RecurrenceFrequency = RecurrenceFrequency.NONE
    interval: int = 1  # every N frequencies (e.g. every 2 weeks)
    by_weekdays: tuple[int, ...] = ()  # 0=Mon, 6=Sun (Python convention)
    count: int | None = None  # max number of occurrences
    until: datetime | None = None  # end date
    rule_version: int = 1

    def is_recurring(self) -> bool:
        return self.frequency != RecurrenceFrequency.NONE

    def next_occurrence_after(self, t: datetime) -> datetime | None:
        """Compute the next occurrence strictly after time t.

        Returns None if rule has ended (count/until exceeded).
        """
        if self.frequency == RecurrenceFrequency.NONE:
            return None

        # Simple implementation for MVP — full RRULE in 0.5+
        if self.frequency == RecurrenceFrequency.DAILY:
            candidate = t + timedelta(days=self.interval)
            candidate = candidate.replace(hour=9, minute=0, second=0, microsecond=0)
        elif self.frequency == RecurrenceFrequency.WEEKLY:
            candidate = t + timedelta(weeks=self.interval)
            candidate = candidate.replace(hour=9, minute=0, second=0, microsecond=0)
        elif self.frequency == RecurrenceFrequency.MONTHLY:
            # Approximate — use 30 days
            candidate = t + timedelta(days=30 * self.interval)
            candidate = candidate.replace(hour=9, minute=0, second=0, microsecond=0)
        elif self.frequency == RecurrenceFrequency.YEARLY:
            candidate = t.replace(year=t.year + self.interval)
        else:
            return None

        # Check until
        if self.until and candidate > self.until:
            return None

        return candidate


# ──────────────────────────────────────────────────────────────────────────────
# Reminder
# ──────────────────────────────────────────────────────────────────────────────


@dataclass
class Reminder:
    """Reminder entity (per docs/07 §1).

    A Reminder is the user's intent to be notified. Concrete instances are
    ReminderOccurrence rows generated by the scheduler.

    Invariants:
    - next_due_at must be in the future when status=ACTIVE
    - recurrence_rule must be present if status=ACTIVE and frequency != NONE
    - timezone must be a valid IANA timezone string
    """

    id: UUID
    workspace_id: UUID
    created_by_user_id: UUID
    title: str
    description: str | None = None
    timezone: str = "UTC"
    recurrence_rule: RecurrenceRule = field(default_factory=RecurrenceRule)
    priority: ReminderPriority = ReminderPriority.NORMAL
    channel: ReminderChannel = ReminderChannel.MOCK
    recipient_ref: str | None = None
    status: ReminderStatus = ReminderStatus.ACTIVE
    source_memory_id: UUID | None = None
    next_due_at: datetime | None = None
    provenance: Provenance = Provenance.EXPLICIT_USER_INPUT
    authority: Authority = Authority.EXPLICIT
    sensitivity: Sensitivity = Sensitivity.PERSONAL
    created_at: datetime = field(default_factory=utc_now)
    updated_at: datetime = field(default_factory=utc_now)
    completed_at: datetime | None = None
    cancelled_at: datetime | None = None
    # Sync fields (present from day 1 per ADR-0005, used for audit/export even without sync)
    version: int = 1
    device_id: str | None = None

    def __post_init__(self) -> None:
        """Validate invariants."""
        if not self.title or not self.title.strip():
            raise ValueError("Reminder title cannot be empty")
        if self.status == ReminderStatus.ACTIVE and self.next_due_at is None:
            # Allow None for newly created reminders before scheduler computes it
            pass

    def complete(self) -> None:
        """Mark the reminder as completed."""
        if self.status not in (ReminderStatus.ACTIVE, ReminderStatus.PAUSED):
            raise ValueError(f"Cannot complete reminder in status {self.status}")
        self.status = ReminderStatus.COMPLETED
        self.completed_at = utc_now()
        self.updated_at = utc_now()
        self.version += 1

    def cancel(self) -> None:
        """Cancel the reminder."""
        if self.status in (ReminderStatus.COMPLETED, ReminderStatus.CANCELLED):
            raise ValueError(f"Cannot cancel reminder in status {self.status}")
        self.status = ReminderStatus.CANCELLED
        self.cancelled_at = utc_now()
        self.updated_at = utc_now()
        self.version += 1

    def pause(self) -> None:
        """Pause the reminder (no new occurrences generated while paused)."""
        if self.status != ReminderStatus.ACTIVE:
            raise ValueError(f"Cannot pause reminder in status {self.status}")
        self.status = ReminderStatus.PAUSED
        self.updated_at = utc_now()
        self.version += 1

    def resume(self) -> None:
        """Resume a paused reminder."""
        if self.status != ReminderStatus.PAUSED:
            raise ValueError(f"Cannot resume reminder in status {self.status}")
        self.status = ReminderStatus.ACTIVE
        self.updated_at = utc_now()
        self.version += 1

    def snooze(self, until: datetime) -> None:
        """Snooze the reminder until a future time."""
        if self.status != ReminderStatus.ACTIVE:
            raise ValueError(f"Cannot snooze reminder in status {self.status}")
        if until <= utc_now():
            raise ValueError("Snooze time must be in the future")
        self.next_due_at = until
        self.updated_at = utc_now()
        self.version += 1


# ──────────────────────────────────────────────────────────────────────────────
# ReminderOccurrence
# ──────────────────────────────────────────────────────────────────────────────


@dataclass
class ReminderOccurrence:
    """Concrete instance of a reminder at a specific time (per docs/07).

    occurrence_key is DETERMINISTIC: {reminder_id}:{due_at_utc_iso}:{rule_version}.
    This is the idempotency key for delivery — same key means same occurrence,
    so duplicate deliveries are detected.
    """

    id: UUID
    reminder_id: UUID
    workspace_id: UUID
    occurrence_key: str
    due_at: datetime
    timezone: str = "UTC"
    status: OccurrenceStatus = OccurrenceStatus.PENDING
    attempts: int = 0
    delivered_at: datetime | None = None
    last_error_code: str | None = None
    created_at: datetime = field(default_factory=utc_now)
    updated_at: datetime = field(default_factory=utc_now)

    @classmethod
    def generate_key(cls, reminder_id: UUID, due_at: datetime, rule_version: int = 1) -> str:
        """Compute the deterministic occurrence_key.

        This is the idempotency guarantee: same reminder + same time + same rule
        always produces the same key, so duplicate scheduler ticks don't create
        duplicate occurrences.
        """
        due_iso = due_at.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        return f"{reminder_id}:{due_iso}:v{rule_version}"

    def mark_delivered(self) -> None:
        """Mark this occurrence as delivered."""
        if self.status in (OccurrenceStatus.DELIVERED, OccurrenceStatus.COMPLETED):
            raise ValueError(f"Occurrence already in terminal status {self.status}")
        self.status = OccurrenceStatus.DELIVERED
        self.delivered_at = utc_now()
        self.updated_at = utc_now()

    def mark_failed(self, error_code: str) -> None:
        """Mark this occurrence as failed (after retries exhausted)."""
        self.status = OccurrenceStatus.FAILED
        self.last_error_code = error_code
        self.attempts += 1
        self.updated_at = utc_now()

    def mark_snoozed(self) -> None:
        """Mark as snoozed (will be rescheduled)."""
        self.status = OccurrenceStatus.SNOOZED
        self.updated_at = utc_now()

    def mark_completed(self) -> None:
        """Mark as completed (user confirmed)."""
        self.status = OccurrenceStatus.COMPLETED
        self.updated_at = utc_now()

    def is_past_due(self) -> bool:
        """Check if this occurrence is past its due time."""
        return utc_now() >= self.due_at
